In [ ]:
#import necessary libraries 
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 
# matplot for plots and graphs 
import seaborn as sns

In [ ]:
#importing dataset in kaggle
data = pd.read_csv('/kaggle/input/kenya-expenditure-data-raw/Kenyan_data.csv')
#data is my dataframe

In [ ]:
data.head(30)

In [ ]:
data.shape

In [ ]:
# check for missing values on  datasets
data.isnull().sum()

Handling Missing Values:
1.data['travel_with'] = data['travel_with'].fillna('Alone'):
•Fills missing values in the travel_with column with the string "Alone". This assumes that "Alone" is a reasonable default value for this column. 
2.data['total_female'] = data['total_female'].fillna(1.0):
•Fills missing values in the total_female column with the number 1.0. This assumes there's at least one female present when the value is missing.This is accurate according to the data . 
3.data['total_male'] = data['total_male'].fillna(1.0):
•Similar to above, fills missing values in the total_male column with 1.0. 
4.data['most_impressing'] = data['most_impressing'].fillna('No comments'):
•Replaces missing values in the most_impressing column with the string "No comments". 
5.data['age_group'] = data['age_group'].replace('24-Jan', '1-24'):
•Replaces occurrences of "24-Jan" in the age_group column with "1-24".

In [ ]:
# Clearing errors and missing values from data set
# For the travel_with and most_impressing columns, fill in with a new category, None
data['travel_with'] = data['travel_with'].replace(np.nan, 'Alone')
#replacing the nan values in the total_female column of the training data with 1.0

data['total_female'] = data['total_female'].replace(np.nan, 1.0)
#replacing the nan values in the total_male column of the training data with 1.0

data['total_male'] = data['total_male'].replace(np.nan, 1.0)

#replacing the nan values in the most_impressing column of the training data with No comments

data['most_impressing'] = data['most_impressing'].replace(np.nan, 'No comments')
#replacing 24-jan to 1-24 to correlate with 

data['age_group'] = data['age_group'].replace('24-Jan', '1-24')
# %convert float dtypes to int[total_female,total_male,night_mainland,night_zanzibar]
data["total_female"] = data['total_female'].astype('int')
data["total_male"] = data['total_male'].astype('int')
data["nights_stayed"] = data['nights_stayed'].astype('int')
# %Let's generate new features from some columns which makes some sense
data["total_people"] = data["total_female"] + data["total_male"]


#chech for missing values
data.isnull().sum()
# %then it's time to encode objects into numeric

In [ ]:
#The mean, standard deviation, minimum, maximum and percentiles of the dataset are described below.
data.describe().T

Statistic: This column lists the different statistical measures calculated for the numerical columns in the dataset (total_female, total_male, and nights_stayed).

count: This represents the number of non-missing values in each column. In this case, all columns have 4 or 5 values (likely because you requested the first 30 rows using data.head(30) and there might be missing values in some rows beyond that).

mean: This is the average value for each column. For example, the average number of females (total_female) is 2.0, the average number of males (total_male) is 1.25, and the average number of nights stayed (nights_stayed) is 9.0.

std: This represents the standard deviation, which measures how spread out the data is from the mean. A higher standard deviation indicates more variability in the data.


min: This is the minimum value in each column. For example, the minimum number of females is 1.0, the minimum number of males is 1.0, and the minimum number of nights stayed is 5.0.


25% (also called the first quartile): This represents the value below which 25% of the data falls. So, in nights_stayed, 25% of the values are less than or equal to 7.

50% (also called the median): This is the middle value when the data is ordered from smallest to largest. It represents the point where 50% of the data falls below and 50% falls above.

75% (also called the third quartile): This represents the value below which 75% of the data falls.

max: This is the maximum value in each column. For example, the maximum number of females is 3.0, the maximum number of males is 2.0, and the maximum number of nights stayed is 14.0.

Understanding this table provides a summary of the central tendency (mean and median) and spread (standard deviation) of the data for the numerical columns (total_female, total_male, and nights_stayed). It also shows the minimum and maximum values, along with percentiles that give you an idea of how the data is distributed.

In [ ]:
# convert float dtypes to int[total_female,total_male,nights_stayed,total_people]
data["total_female"] = data['total_female'].astype('int')
data["total_male"] = data['total_male'].astype('int')
data["nights_stayed"] = data['nights_stayed'].astype('int')
data["total_people"] = data['total_people'].astype('int')

This code  efficiently converts the data types of specific columns in your DataFrame data from float (decimal numbers) to integer (whole numbers).

In [ ]:
data.country = data.country.replace("SWIZERLAND", "SWITZERLAND")
data.country = data.country.replace("BURGARIA","BULGARIA")
data.country = data.country.replace("MALT","MALTA")
data.country = data.country.replace("DRC","DEMOCRATIC REPUBLIC OF THE CONGO")
data.country = data.country.replace("DRC","DEMOCRATIC REPUBLIC OF THE CONGO")
data.country = data.country.replace("SCOTLAND","UNITED KINGDOM")
data.country = data.country.replace("UAE","UNITED ARAB EMIRATES")
data.country = data.country.replace("PHILIPINES","PHILIPPINES")
data.country = data.country.replace("DJIBOUT","DJIBOUTI")
data.country = data.country.replace("MORROCO","MOROCCO")
data.age_group=data.age_group.replace("Jan-24","1-24")

In [ ]:
data.info()

Data Validation: It's a good practice to check your data after conversion to ensure there are no unexpected issues. Make sure the values in these columns are indeed whole numbers and don't contain any decimals after the conversion.

Explorative data analysis 
UNIVARIATE ANALYSIS FOR NUMERICAL DATA ON DATASET

WHAT IS THE INFO SOURCE OF TOURIST?

sns.countplot(...): This function creates a count plot using seaborn, which is a type of bar plot that shows the count of observations in each category. It counts the occurrences of different categories of data and displays them as bars.


sns.barplot is a function provided by the Seaborn library in Python for creating bar plots. Bar plots are used to visualize the relationship between a categorical variable and a continuous variable


plt.legend(loc='center left', bbox_to_anchor=(1, 0.5)): This line adds a legend to the plot. It specifies the location of the legend to be 'center left' and positions it outside the plot using the bbox_to_anchor parameter. This is useful when the legend overlaps with the plot content.

data=data: Specifies the DataFrame data from which the data will be drawn.


plt.legend(...): This function adds a legend to the plot, which helps in identifying the different categories represented by the colors in the plot.

loc='center left': Specifies the location of the legend to be 'center left', which means it will be placed to the left of the plot.
bbox_to_anchor=(1, 0.5): Specifies the position of the legend relative to the plot area. Here, (1, 0.5) means the legend will be anchored at the point (1, 0.5) of the plot, which is the far-right side and vertically centered.

plt.xticks(rotation=90): Rotates the x-axis labels by 90 degrees for better readability. This is often necessary when the x-axis labels are long or numerous to prevent overlapping.


 sns.set_style("darkgrid"), you are configuring Seaborn to apply the "darkgrid" style to all subsequent plots created using Seaborn in the current session, unless the style is explicitly changed again later. This helps ensure consistency in the appearance of your plots throughout your data analysis or visualization process.

In [ ]:
#info source of the tourist 

# Set the style
sns.set_style("darkgrid")

# Create the count plot
info_sources = sns.countplot(x='info_source', data=data, palette=['blue', 'green'])
# Get the patches and set facecolor for the tallest patch
patch_h = [patch.get_height() for patch in info_sources.patches]
idx_tallest = np.argmax(patch_h)
info_sources.patches[idx_tallest].set_facecolor('#a834a8')

# Rotate the x-axis labels
plt.xticks(rotation=90)

# Show the plot
plt.show()

idx_tallest = np.argmax(patch_h): This line uses NumPy's argmax function to find the index of the tallest patch among a collection of patches. patch_h is likely an array or list containing the heights of each patch.

info_sources.patches[idx_tallest]: This part accesses the patch object at the index idx_tallest within the info_sources object. info_sources could be a container (e.g., a plot or a figure) holding multiple patches.

.set_facecolor('#a834a8'): This method sets the face color of the patch identified by info_sources.patches[idx_tallest] to the hexadecimal color '#a834a8', which represents a shade of purple.

The highest coun of information source for tourist visiting kenya is travel agent and tour operator. There is a lowcount of publicity using media source.

In [ ]:


# Group by 'info_source' and calculate the sum of 'total_cost', then select the top 5 largest
top_info_sources = data.groupby('info_source')['total_cost'].sum().nlargest(5)

# Create a pie chart
plt.figure(figsize=(8, 8))
plt.pie(top_info_sources, labels=top_info_sources.index, autopct='%1.2f%%', shadow=True)
plt.title('Top 5 Information Sources by Total Cost')
plt.axis('equal')  # Equal aspect ratio ensures that pie is drawn as a circle.
plt.show()

In [ ]:
#What are the top 5 countries with the highest spending statistic ?
data_country = data.groupby('country')['total_cost'].sum().sort_values(ascending = False).head(6)
data_country

In [ ]:


# Set seaborn style
plt.style.use('seaborn')

# Define a custom color palette with many colors
colors = sns.color_palette('husl', len(data_country))

# Plot the data with custom colors
data_country.plot(figsize=(6, 3), legend=False, kind='bar', color=colors)

# Set title
plt.title('Showing the top six countries with highest spending')

# Show plot
plt.show()

In [ ]:
#which age-group are the highest spenders and who are the over all highest spenders by travel with?
data_age = data.groupby('age_group')['total_cost'].sum().sort_values(ascending = False)
data_age

In [ ]:

# Plot the bar plot with purple color and black edge
data_age.plot.bar(edgecolor='black', color='purple', grid=False, figsize=(4, 2))

plt.title('Spenders by Age Group', color='purple')  # Set title with purple color
plt.xticks(rotation='horizontal')  # Rotate x-axis labels horizontally
plt.show()

In [ ]:
45-64 age_group are the highest spenders while 1-24 age group are the least spenders

In [ ]:
#data['age_group'].value_counts() gives you a count of how many times each age group appears in the 'age_group' column of the DataFrame data.
data['age_group'].value_counts()

In [ ]:
#unexploded pie
#data.value_counts('age_group').plot(kind = 'pie', autopct = '%1.2f%%')


data['age_group'].value_counts().plot(kind='pie', autopct='%1.2f%%', explode=(0.1, 0, 0, 0))

# Add title
plt.title('Distribution of Age Groups')

# Show the plot
plt.show()

The pie chart shows that the majority age group is 25 -44 and the least age group is 65+

In [ ]:
sns.countplot(x = 'age_group', hue = 'travel_with', data = data)
plt.legend(loc = 'center left', bbox_to_anchor = (1,0.5))
plt.title('age group of tourist by travel with ')
plt.figure(figsize = (6,3))
plt.show()

Age group 25 - 44 has the highest count of tourist who travelled alone, friend/relatives, spouse and age group 65+ has a least count of tourist who travelled with wife and children

In [ ]:
data_age_group = data.groupby(['age_group', 'travel_with'])['total_cost'].sum()
data_age_group
# age goup with repect to travel with total spendings

In [ ]:
data_travel_with = data.groupby('travel_with')['total_cost'].sum().sort_values(ascending = False)
data_travel_with
#data_travel_with will display the result, showing the total cost associated with each unique value in the 'travel_with' column, sorted from highest to lowes

In [ ]:
plt.style.use('seaborn')
data_travel_with.plot(kind = 'bar', legend = False, colormap = 'winter', figsize = (6,3))
plt.title('total cost against travel with')
plt.show()

Tourist who travel with their spouse are the most spenders

In [ ]:
sns.barplot(y = 'total_cost', x = 'age_group',  hue = 'travel_with', data = data)
plt.legend(loc = 'center left', bbox_to_anchor = (1,0.5))
plt.title('Bar plot of total cost and age group of travel with tourist')
plt.show()

Tourist who are 65+ and having spouse spend the highest cost, tourist in the age group of 25-44 who are alone spend the least

In [ ]:
data_main_activity = data.groupby('main_activity')['total_cost'].sum().sort_values(ascending = False)
data_main_activity

In [ ]:
plt.style.use('seaborn')
data_main_activity.plot(kind='bar', legend=False, color='orange', figsize=(6, 3))
plt.title('Total Cost against Main Activity')
plt.show()

In [ ]:

#what is the most prefered payment mode by tourists?
sns.countplot(x = 'payment_mode', data = data)

In [ ]:
######Highlight the Aspects of tourism that are more profitable and in which it is worthwhile to invest in
sns.countplot(x = 'main_activity', data = data)
plt.xticks(rotation = 90)
plt.show()

In [ ]:
# considering the purpose
sns.countplot(x = 'purpose', data = data)
plt.xticks(rotation = 90, fontsize = 8 )
plt.title('purpose of visiting Kenya')
plt.show()

In [ ]:
sns.countplot( x = 'purpose', hue = 'main_activity', data = data)
plt.legend(loc = 'center left', bbox_to_anchor = (1,0.5))
plt.xticks (rotation =90)
plt.show()

the code creates a count plot to visualize the distribution of purposes of visiting (x-axis) based on different main activities (grouped bars). It adds a legend to help identify the main activities, rotates the x-axis labels for readability, and then displays the plot.

In [ ]:
sns.barplot(x = 'purpose', y = 'total_cost', hue = 'main_activity', data = data)
plt.legend(loc = 'center left', bbox_to_anchor = (1,0.5))
plt.xticks (rotation =90)
plt.show()

sns.countplot(x='age_group', hue='travel_with', data=data): This line creates a countplot using seaborn (sns). It plots the count of observations for each category in the 'age_group' column, with bars grouped by the 'travel_with' column. It uses the data provided in the data DataFrame.

plt.legend(loc='center left', bbox_to_anchor=(1, 0.5)): This line adds a legend to the plot. The loc='center left' parameter specifies the location of the legend to be at the center left of the plot, and bbox_to_anchor=(1, 0.5) specifies the anchor point of the legend box to be at the specified coordinates relative to the plot area.

plt.title('Age Group of Tourists by Travel With'): This line sets the title of the plot to 'Age Group of Tourists by Travel With'.

plt.figure(figsize=(6, 3)): This line sets the size of the figure (plot) to be displayed. The figsize parameter specifies the width and height of the figure in inches. Here, the width is 6 inches, and the height is 3 inches.

plt.show(): This line displays the plot.

In [ ]:

#model Building
for colname in data.select_dtypes("object"):
    data[colname],_=data[colname].factorize()
# Now all columns that can be converted to numeric have been converted
# Step 3 model building

1. Identifying Textual Columns:

data.select_dtypes("object"): This part selects all columns in the DataFrame data that have the data type "object". In pandas, "object" typically represents text-based columns, which often need conversion before being used in model building.
2. Converting to Numeric:

The for loop iterates through each column name (colname) identified in step 1:
data[colname], _ = data[colname].factorize(): This line applies the factorize method to each textual column.
factorize assigns a unique integer to each unique value in the column. This transforms the text data into numerical categories, making it compatible with many machine learning models that require numerical inputs.
The underscore (_) is used to discard the second output of factorize, which is an array of unique labels not needed for this task.
3. Numeric Data for Modeling:

The comment # Now all columns that can be converted to numeric have been converted indicates that, after this step, all columns in the DataFrame data have been transformed into either numeric or categorical data types suitable for model building.



This is a common preprocessing step before model building, ensuring your data is in a format that machine learning algorithms can process effectively.

In [ ]:
data.head()

In [ ]:
numeric_columns = data.select_dtypes(include='number').columns
print(numeric_columns)

Independent Variables:

Country: This categorical variable represents the tourist's country of origin. It likely influences travel costs due to factors like distance, airfare, and currency exchange rates.

Age group: This categorical variable represents the age range of the tourist(s). It might influence costs related to preferences, travel styles, and potential discounts for age groups.

Travel with: This categorical variable indicates who the tourist is traveling with (alone, family, friends, etc.). This can affect costs due to differences in accommodation choices, activity preferences, and group discounts.

Total female: This numerical variable represents the number of females in the travel group. It might influence costs related to accommodation pricing and activity choices.


Total male: This numerical variable represents the number of males in the travel group. Similar to total_female, it can affect costs related to accommodation and activities.


Purpose: This categorical variable indicates the primary purpose of the trip (e.g., scenery, culture, wildlife). It can influence costs depending on the types of activities and locations associated with the purpose.


Main activity: This categorical variable represents the tourist's main activity during the trip. Similar to purpose, it can affect costs based on the types of activities chosen.

Info source: This categorical variable indicates where the tourist obtained information about the trip. It likely doesn't directly influence the cost itself but might be indirectly related to travel style or preferences.

Tour arrangement: This categorical variable indicates whether the trip was booked as a package tour or arranged independently. Package tours might have different cost structures compared to independent travel.

Package transport international: This categorical variable (possibly yes/no) indicates whether international transportation was included in a package tour. If applicable, it affects the overall cost.

Package accommodation: Similar to package transport international, this indicates whether accommodation was included in a package tour, influencing the cost.

Package food: Similar to the above, this indicates whether meals were included in a package tour.

Package transport local: This indicates whether local transportation was included in a package tour, affecting the cost.


Package sightseeing: Similar to the above, this indicates whether sightseeing tours were included in a package tour.

Package guided tour: This indicates whether guided tours were included in a package tour, affecting the cost.

Package insurance: Similar to the above, this indicates whether travel insurance was included in a package tour.

Nights stayed: This numerical variable represents the total number of nights spent at the destination. It's a significant factor influencing accommodation costs.

Payment mode: This categorical variable indicates the payment method used for the trip (e.g., cash, credit card). It likely doesn't directly influence the overall cost but might be related to exchange rates or fees.

First trip: This categorical variable (possibly yes/no) indicates whether this is the tourist's first trip to the destination. It might influence costs depending on familiarity with the location and travel style.

Dependent Variable:

Total cost: This numerical variable represents the total cost of the trip, which is what the model is trying to predict based on the independent variables listed above.

 The model uses various characteristics of the tourist (country, age, travel companions, etc.), trip details (purpose, activities, package options), and travel behavior (length of stay, payment method) to predict the total cost of the trip.

In [ ]:
#ignore warnings
import warnings
warnings.filterwarnings('ignore')
x= data.drop("total_cost", axis=1)
y = data.pop("total_cost")
#after executing these two lines of code, 
#x will contain the features (independent variables) of the dataset, 
#while y will contain the target variable (dependent variable) "total_cost".
#This is a common approach in supervised learning tasks where you separate the features and target variable to prepare the data for training a machine learning model.

In [ ]:
print(y.value_counts())

In [ ]:
#Convert categorical variables to dummy variables
x = pd.get_dummies(x, drop_first=True)
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.30,random_state=42)

The code snippet x = pd.get_dummies(x, drop_first=True) applies one-hot encoding to convert the categorical variables in your data frame x into dummy variables. Here's a breakdown of what it does:

One-Hot Encoding:

It's a technique for representing categorical variables as binary vectors.
Each category within a categorical variable gets its own column in the transformed data.
The values in these new columns are either 0 (absence of the category) or 1 (presence of the category).
Arguments:

x: This is the DataFrame containing your data, where you want to convert categorical variables to dummy variables.
drop_first=True: This argument is set to True in the code. It instructs the get_dummies function to drop the first level of each categorical variable when creating dummy variables. This helps avoid redundancy and potential multicollinearity issues in machine learning models.

Benefits of One-Hot Encoding:

Makes categorical variables interpretable by machine learning models that work with numerical features.
Simplifies model training by converting categorical data into a format suitable for numerical computations.
Splitting Data (Following Lines):

The subsequent lines x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.30,random_state=42) perform train-test splitting on your data. Here's what each part does:

x_train: This variable stores the features (including the newly created dummy variables) for the training set.

x_test: This variable stores the features for the testing set.

y_train: This variable stores the target variable (total cost) for the training set.

y_test: This variable stores the target variable for the testing set.

train_test_split: This is a function from scikit-learn that helps split your data into training and testing sets.

test_size=0.30: This argument specifies that 30% of the data will be used for testing, and the remaining 70% will be used for training.

random_state=42: This argument sets a random seed for splitting the data. This ensures reproducibility if you run the code multiple times.

Convert Categorical Variables to Dummy Variables: It uses pd.get_dummies() function from the Pandas library to convert categorical variables in the DataFrame x into dummy variables.

Dummy variables are binary variables representing the categories of the original categorical variables.
The drop_first=True parameter is used to drop the first category of each categorical variable to avoid multicollinearity issues.

Split Data into Training and Testing Sets: It then splits the dataset into training and testing sets using the train_test_split() function from the sklearn.model_selection module. The test_size=0.30 parameter specifies that 30% of the data will be used for testing, and the remaining 70% will be used for training. The random_state=42 parameter sets the random seed for reproducibility.

In [ ]:
print (x_train.shape, y_train.shape)
print (x_test.shape, y_test.shape)

In [ ]:
#using catboost
from catboost import CatBoostRegressor
predictions = []
for i in range(10):
  # Training the model
  ct=CatBoostRegressor(iterations=1000, 
                    loss_function='MAE',
                    logging_level='Silent',
                    depth = i
                    )
ct.fit(x_train, y_train)


In the provided code snippet, a CatBoostRegressor model is being trained using the CatBoost library. Here's an explanation of the key components:

Importing CatBoostRegressor: The code starts by importing the CatBoostRegressor class from the catboost library.

Loop for Training: The loop iterates 10 times, presumably to train multiple models with different parameters or configurations.

Model Training: Within each iteration of the loop, a CatBoostRegressor model is instantiated and trained using the fit() method. The parameters specified for the model are as follows:

iterations=1000: Specifies the number of boosting iterations (trees) to be used in the model.
loss_function='MAE': Sets the loss function to Mean Absolute Error (MAE), which is a common choice for regression problems.
logging_level='Silent': Configures the logging level of the training process to be silent, meaning no training progress will be printed to the console.
depth=i: Specifies the depth of the trees in the gradient boosting ensemble. The depth is set dynamically based on the current iteration of the loop.
Training Data: The model is trained using the training data (x_train, y_train).

Predictions List: There is a list named predictions, but it is not being utilized within the loop. It appears that the predictions are not being stored or used for any purpose within this loop. If predictions are intended to be made, they should be performed within the loop, and the results should be appended to the predictions list.

In [ ]:
 # Making predictions
preds = ct.predict(x_test)
predictions.append(preds)

# Averaging the predictions
preds = np.mean(predictions, axis = 0)
preds

In [ ]:
array([ 8612130.63604591,   698445.27304175,  1887972.05868304, ...,
        5915173.34762821,   567511.1297576 , 15136663.35290364])

In [ ]:
# Model evaluation
from sklearn.metrics import mean_absolute_error 
mae = mean_absolute_error(y_test, preds)**0.5
print('Error {}'.format(mae))

Error 2187.181866641503

In [ ]:
# Doing our prediction.
sub = y
predictions_ct = ct.predict(sub)
predictions_ct

8679995.993100591

In [ ]:
# Doing our prediction.
sub = x_test
predictions_ct = ct.predict(sub)
predictions_ct

In [ ]:
from sklearn.model_selection import  train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from catboost import CatBoostRegressor
import math

In [ ]:
#RMSE
Rmse_test = math.sqrt(mean_squared_error(y_test,preds))

#R2 Score
r2_test = r2_score(y_test,preds)

# Adjusted R2 Score
n= x_train.shape[0] # total no of datapoints
p= x_train.shape[1] # total no of independent features
adj_r2_test = 1-(1-r2_test)*(n-1)/(n-p-1)

#print results
mae = mean_absolute_error(y_test, preds)**0.5
print('Error {}'.format(mae))
print("Evaluation on test data")
print("RMSE: {:.2f}".format(Rmse_test))
print('R2: {:.2f}'.format(r2_test))
print("Adjusted R2: {:.2f}".format(adj_r2_test))

Root Mean Squared Error (RMSE): It calculates the square root of the mean squared error between the actual target values (y_test) and the predicted values (preds).

R2 Score: It calculates the coefficient of determination (R2) between the actual target values (y_test) and the predicted values (preds).

Adjusted R2 Score: It adjusts the R2 score to penalize the addition of unnecessary independent variables in the model.

Mean Absolute Error (MAE): It calculates the absolute error between each predicted value and its corresponding actual value, then takes the mean of these absolute errors.

Error 2187.181866641503
Evaluation on test data
RMSE: 9244973.96
R2: 0.39
Adjusted R2: 0.38

In [ ]:
new_prices = x_test.assign(predicted_prices = predictions_ct)
new_prices.head()

In [ ]:
import matplotlib.pyplot as plt

# Create a scatter plot
plt.figure(figsize=(10, 6))
plt.scatter(y_test, preds, color='blue', alpha=0.5)
plt.plot([min(y_test), max(y_test)], [min(y_test), max(y_test)], color='red', linestyle='--')
plt.xlabel('Actual Total Cost')
plt.ylabel('Predicted Total Cost')
plt.title('Actual vs Predicted Total Cost (CatBoostRegressor)')
plt.grid(True)
plt.show()

Using Xgboost

In [ ]:
from sklearn.metrics import mean_absolute_error, r2_score

model_xgb = XGBRegressor()
model_xgb.fit(x_train, y_train)
predictions_xgb = model_xgb.predict(x_test)

# Calculate Mean Absolute Error
mae_xgb = mean_absolute_error(y_test, predictions_xgb) ** 0.5

# Calculate R-squared error
r2_xgb = r2_score(y_test, predictions_xgb)

print('XGBoostRegressor Error:')
print('Mean Absolute Error:', mae_xgb)
print('R-squared Error:', r2_xgb)

In [ ]:
# Create a scatter plot
plt.figure(figsize=(10, 6))
plt.scatter(y_test, predictions_xgb, color='green', alpha=0.5)
plt.plot([min(y_test), max(y_test)], [min(y_test), max(y_test)], color='red', linestyle='--')
plt.xlabel('Actual Total Cost')
plt.ylabel('Predicted Total Cost')
plt.title('Actual vs Predicted Total Cost (XGBoostRegressor)')
plt.grid(True)
plt.show()

The x-axis represents the actual total cost of tourism expenditure in Kenya.
The y-axis represents the predicted total cost of tourism expenditure in Kenya, generated by your XGBoost model.
Each dot in the scatter plot represents a single data point for tourism spending in Kenya. The horizontal position of the dot shows the actual total cost for that instance, and the vertical position shows the predicted total cost from the model.
Interpretation:

A perfect alignment would result in all data points falling exactly on a diagonal line from the bottom left (low predicted cost, low actual cost) to the top right (high predicted cost, high actual cost). This would indicate that the model's predictions perfectly match the actual total costs.

In [ ]:
for linear regression 
r2 score (R2):  0.3153762520519584
mean_sqrd_error (MSE):  95342127884183.06
mean_absolute_error (MAE):  5742305.016385339
root_mean_squared error (RMSE):  9764329.36172183
    
    XGBoostRegressor Error:
Mean Absolute Error: 2368.682176983154
R-squared Error: 0.2798689384401998
    
    Error 2182.6442791688637
Evaluation on test data
RMSE: 9316109.87
R2: 0.38
Adjusted R2: 0.37

data.head()